# Generated by Django 5.2.5 on 2025-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_sellingpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='selling_posts/'),
        ),
    ]
